In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('OnlineNewsPopularity.csv')
dataset.head()

url   timedelta  \
0  http://mashable.com/2013/01/07/amazon-instant-...       731.0   
1  http://mashable.com/2013/01/07/ap-samsung-spon...       731.0   
2  http://mashable.com/2013/01/07/apple-40-billio...       731.0   
3  http://mashable.com/2013/01/07/astronaut-notre...       731.0   
4   http://mashable.com/2013/01/07/att-u-verse-apps/       731.0   

    n_tokens_title   n_tokens_content   n_unique_tokens   n_non_stop_words  \
0             12.0              219.0          0.663594                1.0   
1              9.0              255.0          0.604743                1.0   
2              9.0              211.0          0.575130                1.0   
3              9.0              531.0          0.503788                1.0   
4             13.0             1072.0          0.415646                1.0   

    n_non_stop_unique_tokens   num_hrefs   num_self_hrefs   num_imgs  ...  \
0                   0.815385         4.0              2.0        1.0  ...   
1                   0.791946         3.0              1.0        1.0  ...   
2                   0.663866         3.0              1.0        1.0  ...   
3                   0.665635         9.0              0.0        1.0  ...   
4                   0.540890        19.0             19.0       20.0  ...   

    min_positive_polarity   max_positive_polarity   avg_negative_polarity  \
0                0.100000                     0.7               -0.350000   
1                0.033333                     0.7               -0.118750   
2                0.100000                     1.0               -0.466667   
3                0.136364                     0.8               -0.369697   
4                0.033333                     1.0               -0.220192   

    min_negative_polarity   max_negative_polarity   title_subjectivity  \
0                  -0.600               -0.200000             0.500000   
1                  -0.125               -0.100000             0.000000   
2                  -0.800               -0.133333             0.000000   
3                  -0.600               -0.166667             0.000000   
4                  -0.500               -0.050000             0.454545   

    title_sentiment_polarity   abs_title_subjectivity  \
0                  -0.187500                 0.000000   
1                   0.000000                 0.500000   
2                   0.000000                 0.500000   
3                   0.000000                 0.500000   
4                   0.136364                 0.045455   

    abs_title_sentiment_polarity   shares  
0                       0.187500      593  
1                       0.000000      711  
2                       0.000000     1500  
3                       0.000000     1200  
4                       0.136364      505  

[5 rows x 61 columns]

In [4]:
dataset.columns = dataset.columns.str.strip()

X = dataset.drop('shares', axis=1).values
y = dataset['shares'].values
print("Матрица признаков:");print(X)
print("Зависимая переменная:");print(y)

Матрица признаков:
[['http://mashable.com/2013/01/07/amazon-instant-video-browser/' 731.0
  12.0 ... -0.1875 0.0 0.1875]
 ['http://mashable.com/2013/01/07/ap-samsung-sponsored-tweets/' 731.0 9.0
  ... 0.0 0.5 0.0]
 ['http://mashable.com/2013/01/07/apple-40-billion-app-downloads/' 731.0
  9.0 ... 0.0 0.5 0.0]
 ...
 ['http://mashable.com/2014/12/27/son-pays-off-mortgage/' 8.0 10.0 ...
  0.136363636364 0.0454545454545 0.136363636364]
 ['http://mashable.com/2014/12/27/ukraine-blasts/' 8.0 6.0 ... 0.0 0.5
  0.0]
 ['http://mashable.com/2014/12/27/youtube-channels-2015/' 8.0 10.0 ...
  0.25 0.166666666667 0.25]]
Зависимая переменная:
[ 593  711 1500 ... 1900 1100 1300]


In [5]:
from sklearn.impute import SimpleImputer
import numpy as np

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')  
imputer = imputer.fit(X[:, 1:3])                                 
X[:, 1:3] = imputer.transform(X[:, 1:3])                         

print(X)

[['http://mashable.com/2013/01/07/amazon-instant-video-browser/' 731.0
  12.0 ... -0.1875 0.0 0.1875]
 ['http://mashable.com/2013/01/07/ap-samsung-sponsored-tweets/' 731.0 9.0
  ... 0.0 0.5 0.0]
 ['http://mashable.com/2013/01/07/apple-40-billion-app-downloads/' 731.0
  9.0 ... 0.0 0.5 0.0]
 ...
 ['http://mashable.com/2014/12/27/son-pays-off-mortgage/' 8.0 10.0 ...
  0.136363636364 0.0454545454545 0.136363636364]
 ['http://mashable.com/2014/12/27/ukraine-blasts/' 8.0 6.0 ... 0.0 0.5
  0.0]
 ['http://mashable.com/2014/12/27/youtube-channels-2015/' 8.0 10.0 ...
  0.25 0.166666666667 0.25]]


In [8]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
print("Зависимая переменная до обработки")
print(y)
y = labelencoder_y.fit_transform(y)
print("Зависимая переменная после обработки")
print(y)

Зависимая переменная до обработки
[448 566 860 ... 864 856 858]
Зависимая переменная после обработки
[448 566 860 ... 864 856 858]


In [10]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print("Матрица признаков (фрагмент):")
print(X[:5])
print("Зависимая переменная (фрагмент):")
print(y[:5])

Матрица признаков (фрагмент):
[['http://mashable.com/2013/01/07/amazon-instant-video-browser/' 731.0
  12.0 219.0 0.663594466988 0.999999992308 0.815384609112 4.0 2.0 1.0 0.0
  4.6803652968 5.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 496.0 496.0 496.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.500331204081 0.378278929586 0.0400046751006 0.0412626477296
  0.0401225435029 0.521617145481 0.0925619834711 0.0456621004566
  0.013698630137 0.769230769231 0.230769230769 0.378636363636 0.1 0.7
  -0.35 -0.6 -0.2 0.5 -0.1875 0.0 0.1875]
 ['http://mashable.com/2013/01/07/ap-samsung-sponsored-tweets/' 731.0 9.0
  255.0 0.604743080614 0.999999993289 0.79194630341 3.0 1.0 1.0 0.0
  4.9137254902 4.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.799755687423
  0.0500466753998 0.0500962518137 0.0501006734234 0.0500007119405
  0.341245791246 0.148947811448 0.043137254902 0.0156862745098
  0.733333333333 0.266666666667 0.28691460